from object_config import *

# Testing Copiable Effect Generated By "As ... enters the battlefield" abilities which
# set power and toughness.

lost_order_of_jarkeld = LostOrderOfJarkeld(p0)

# Outside of the battlefield, Lost Order of Jarkeld's power and toughness are 1+* where * is 0.
assert lost_order_of_jarkeld.power == lost_order_of_jarkeld.toughness == 1

# p0, Lost Order of Jarkeld's owner, casts it, and as it enters the battlefield, choses p1
# as the chosen opponent.
lost_order_of_jarkeld.chosen_opponent = p1
ZH.zone_battlefield.add_object(lost_order_of_jarkeld)

snapshot()
display([lost_order_of_jarkeld])

assert lost_order_of_jarkeld.power == lost_order_of_jarkeld.toughness == 1
# Outcome: p1 doesn't control any creatures so Lost Order of Jarkeld's power and toughness
# are both equal to 1 + 0 == 1.

# p1, the chosen opponent, puts Alpha Myr onto the battlefield under their control.
alpha_myr = AlphaMyr(p1)
ZH.zone_battlefield.add_object(alpha_myr)
snapshot()
display([lost_order_of_jarkeld])

assert lost_order_of_jarkeld.power == lost_order_of_jarkeld.toughness == 2

# Outcome: Lost Order of Jarkeld's power and toughness are both equal to 1 + 1 == 2.
# p1, the chosen opponent, puts Clone onto the battlefield under their control, and
# chooses Lost Order of Jarkeld.

clone = Clone(p1)
clone.copy_source_object = lost_order_of_jarkeld
clone.chosen_opponent = p0
ZH.zone_battlefield.add_object(clone)

snapshot()
display([lost_order_of_jarkeld, clone])

assert lost_order_of_jarkeld.power == lost_order_of_jarkeld.toughness == 3
assert clone.power == clone.toughness == 2

# Outcome: Lost Order of Jarkeld's power and toughness are both equal to 1 + 2 == 3.
# Clone enters as a copy of Lost Order of Jarkeld. 707.6 states, "When copying a permanent,
# any choices that have been made for that permanent aren't copied. Instead, if an object enters
# the battlefield as a copy of another permanent, the object's controller will get to make any
# "as [this] enters the battlefield" choices for it. Clone's controller must choose p0.
# p0 only controls 1 creature. Therefore Clone's power and toughness should be 1 + 1 == 2.
